main: com.westosia.essentials.bukkit.Main
name: Westentials
version: 0.1
authors:
  - TheBirmanator
  - TheMGRF
  - JamieCee
  - Dewgon
api-version: 1.15
description: Essentials but only the essentials
depend: [RedisAPI, DatabaseAPI, CooldownAPI, WestosiaAPI, ACFLoader, MysqlPlayerDataBridge, PremiumVanish]
permissions:
  essentials.*:
    description: Gives access to all Essentials commands and permisions